.TH "CMDSHELF-LIST" "1" "January 2018" "cmdshelf 0.9.2" "Cmdshelf Manual"
.SH "NAME"
cmdshelf-list - Show all registered commands.
.SH "SYNOPSIS"
\fIcmdshelf list\fR [\-\-path]
.SH "DESCRIPTION"
.TP
The list subcommand lists all commands from remotes and blobs.
.SH "OPTIONS"
.TP
\-\-path
.RS 4
Print absolute paths for each commands.
