.TH "CMDSHELF-CAT" "1" "February 2018" "cmdshelf 0.9.3" "Cmdshelf Manual"
.SH "NAME"
cmdshelf-cat - Concatenate and print command(s).
.SH "SYNOPSIS"
\fBcmdshelf cat\fR [[<remoteName>:]<command>]
.SH "DESCRIPTION"
.TP
The cat subcommand reads commands script files sequentially, writing them to the standard output.
