.TH "CMDSHELF-BLOB" "1" "February 2018" "cmdshelf 0.9.3" "Cmdshelf Manual"
.SH "NAME"
cmdshelf-blob - Manage blobs
.SH "SYNOPSIS"
\fBcmdshelf blob\fR <command> [<args>]
.SH "DESCRIPTION"
.TP
The blob subcommand manages blobs.
.SH "SUB-COMMANDS"
.SS add <name> <url>
Add a blob named <name> at <url>. <url> can be a network URL or a local filepath.
.SS list
List blobs.
.SS remove <name>
Remove the blob named <name>.
