.TH "CMDSHELF-REMOTE" "1" "February 2018" "cmdshelf 0.9.6" "Cmdshelf Manual"
.SH "NAME"
cmdshelf-remote - Manage set of tracked repositories
.SH "SYNOPSIS"
.sp
.nf
\fBcmdshelf remote add\fR <name> <url>
\fBcmdshelf remote list\fR
\fBcmdshelf remote remove\fR <name>
.fi
.sp
.SH "DESCRIPTION"
.TP
Manage the set of repositories ("remotes").
.SH "SUB-COMMANDS"
.SS add
Adds a remote named <name> for the repository at <url>.
.SS list, ls
List tracked remotes.
.SS remove, rm
Remove the remote named <name>. This won't remove the local repository. Clean on your own if needed.
