.TH "CMDSHELF-BLOB" "1" "February 2018" "cmdshelf 0.9.4" "Cmdshelf Manual"
.SH "NAME"
cmdshelf-blob - Manage blobs
.SH "SYNOPSIS"
.sp
.nf
\fBcmdshelf blob add\fR <name> <url>
\fBcmdshelf blob list\fR
\fBcmdshelf blob remove\fR <name>
.fi
.sp
.SH "DESCRIPTION"
.TP
The blob subcommand manages blobs.
.SH "SUB-COMMANDS"
.SS add
Add a blob named <name> at <url>. <url> can be a network URL or a local filepath.
.SS list, ls
List blobs.
.SS remove, rm
Remove the blob named <name>.
